# Step 5: Data Preparation

* Perform data cleaning and preprocessing:

    o Handle missing user-item interactions

    o Encode categorical attributes (e.g., product categories, user demographics)

    o Normalize numerical variables (e.g., prices, timestamps)

* Conduct exploratory analysis showing interaction distributions, item popularity, and sparsity patterns.


**Deliverables:**
*   Jupyter notebook or script demonstrating cleaning and EDA
*   Summary plots (histograms, heatmaps)
*   Prepared dataset ready for transformation

# 1.   Load Datasets


*   Load the 'users_dirty.csv', 'products_dirty.csv', and 'interactions_dirty.csv' files into pandas DataFrames.
*   Display the first 5 rows and column information for each to verify successful loaded and inspect initial data types.

In [ ]:
%matplotlib inline
#import modules
import pandas as pd
import sys
from pathlib import Path # Ensure Path is imported if not already in config
from datetime import datetime
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

# ... (your existing sys.path and config imports)
sys.path = [
  "/home/abhishek/Documents/Study/dmml_assignment/group_4_dmml",
]
from config import USER_INTERACTION_DIR, USERS_DIR, PRODUCT_DIR,  PROCESSED_INTERACTION_DIR, \
    PROCESSED_USERS_DIR, PROCESSED_PRODUCT_DIR

RuntimeError: 'inline' is not a recognised GUI loop or backend name

In [2]:
# read interactions data files

year = datetime.now().strftime("%Y")
month = datetime.now().strftime("%m")
# day = datetime.now().strftime("%d")
day=10

# 1. Define the directory path (without the filename)
interaction_search_dir = USER_INTERACTION_DIR / f"year={year}" / f"month={month}" / f"day={day}"
users_search_dir = USERS_DIR / f"year={year}" / f"month={month}" / f"day={day}"
products_search_dir = PRODUCT_DIR / f"year={year}" / f"month={month}" / f"day={day}"

# 2. Use glob to find all files matching the pattern
# This returns a generator of Path objects

#2.1 Load users dataset
files = list(users_search_dir.glob("users*.csv"))
if not files:
    print(f"No files found in {users_search_dir}")
else:
    # Read and concatenate all matched files
    df_list = [pd.read_csv(f) for f in files]
    users_df = pd.concat(df_list, ignore_index=True)
    print(f"Successfully loaded {len(files)} file(s).")
    print("\n--- Users DataFrame ---")
    print("First 5 rows:")
    display(users_df.head())
    print("Column information:")
    users_df.info()

#2.2 Load products dataset
files = list(products_search_dir.glob("products*.csv"))
if not files:
    print(f"No files found in {products_search_dir}")
else:
    # Read and concatenate all matched files
    df_list = [pd.read_csv(f) for f in files]
    products_df = pd.concat(df_list, ignore_index=True)
    print(f"Successfully loaded {len(files)} file(s).")
    print("\n--- Products DataFrame ---")
    print("First 5 rows:")
    display(products_df.head())
    print("Column information:")
    products_df.info()

#2.3 Load interaction dataset
files = list(interaction_search_dir.glob("interactions*.csv"))
if not files:
    print(f"No files found in {interaction_search_dir}")
else:
    # Read and concatenate all matched files
    df_list = [pd.read_csv(f) for f in files]
    interactions_df = pd.concat(df_list, ignore_index=True)
    print(f"Successfully loaded {len(files)} file(s).")
    print("\n--- Interactions DataFrame ---")
    print("First 5 rows:")
    display(interactions_df.head())
    print("Column information:")
    interactions_df.info()

Successfully loaded 1 file(s).

--- Users DataFrame ---
First 5 rows:

,user_id,name,email,gender,age,city,signup_date
0,U01898,Aaron Green,susannelson@example.net,F,19.0,Donnabury,2025-08-25
1,U00878,Jason Jenkins,gainesanthony@example.com,Other,26.0,Port Donaldport,2025-08-07
2,U04504,Jeffery Mejia,pwilliams@example.net,F,61.0,Kingville,2024-08-19
3,U04726,Blake Serrano,patricia70@example.net,F,37.0,Amberfurt,2024-12-31
4,U01596,Matthew Ellis,woodwarderin@example.org,F,24.0,New Debbieville,2025-01-06

Column information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5062 entries, 0 to 5061
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      4934 non-null   object
 1   name         4925 non-null   object
 2   email        4937 non-null   object
 3   gender       4936 non-null   object
 4   age          4939 non-null   object
 5   city         4934 non-null   object
 6   signup_date  4952 non-null   object
dtypes: object(7)
memory usage: 277.0+ KB
Successfully loaded 1 file(s).

--- Products DataFrame ---
First 5 rows:

,product_id,product_name,category,brand,price,rating,stock_level
0,P001,Purpose Brother Pro,Electronics,Figueroa and Sons,1114.91,2.0,71
1,P002,Dog Chair Pro,Electronics,"Garcia, Yang and Gardner",889.83,1.1,47
2,P003,Performance Knowledge Max,Fashion,Johnson and Sons,762.98,1.1,101
3,P004,Early Mouth v2,Sports,"Johnson, Gonzalez and Santos",338.46,3.4,414
4,P005,Offer Kind Max,Electronics,Cole LLC,1050.23,2.4,79

Column information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    object
 1   product_name  100 non-null    object
 2   category      100 non-null    object
 3   brand         100 non-null    object
 4   price         100 non-null    float64
 5   rating        100 non-null    float64
 6   stock_level   100 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB
Successfully loaded 1 file(s).

--- Interactions DataFrame ---
First 5 rows:

,interaction_id,user_id,product_id,action,rating,timestamp,device,session_duration_sec
0,INT00016884,U00787,P089,add_to_cart,NaN,2025-10-28 01:21:14.342041,Desktop,873.0
1,INT00069689,U01492,P068,add_to_cart,NaN,2025-12-14 16:16:21.342041,Desktop,835.0
2,INT00054155,U00530,P026,view,3.5,Invalid_Data,Desktop,942.0
3,INT00031470,U01242,P083,view,1.9,2025-11-10 06:03:21.342041,Desktop,572.0
4,INT00048782,U02998,P097,click,NaN,2025-11-25 18:20:58.342041,Tablet,953.0

Column information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101250 entries, 0 to 101249
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   interaction_id        98723 non-null  object
 1   user_id               98757 non-null  object
 2   product_id            98753 non-null  object
 3   action                98735 non-null  object
 4   rating                10186 non-null  object
 5   timestamp             98769 non-null  object
 6   device                98749 non-null  object
 7   session_duration_sec  98756 non-null  object
dtypes: object(8)
memory usage: 6.2+ MB

# 2.   Initial Data Cleaning


*   Perform general data cleaning across all three datasets, including:
*   Handling duplicates
*   Correcting inconsistent data types
*   Addressing basic format errors in columns like dates or emails

In [3]:
print("### 2.1 Handling Duplicates ###")

# users_df
initial_rows_users = users_df.shape[0]
users_df.drop_duplicates(inplace=True)
duplicates_removed_users = initial_rows_users - users_df.shape[0]
print(f"Users DataFrame: {duplicates_removed_users} duplicate rows removed. New shape: {users_df.shape}")

# products_df
initial_rows_products = products_df.shape[0]
products_df.drop_duplicates(inplace=True)
duplicates_removed_products = initial_rows_products - products_df.shape[0]
print(f"Products DataFrame: {duplicates_removed_products} duplicate rows removed. New shape: {products_df.shape}")

# interactions_df
initial_rows_interactions = interactions_df.shape[0]
interactions_df.drop_duplicates(inplace=True)
duplicates_removed_interactions = initial_rows_interactions - interactions_df.shape[0]
print(f"Interactions DataFrame: {duplicates_removed_interactions} duplicate rows removed. New shape: {interactions_df.shape}")

### 2.1 Handling Duplicates ###
Users DataFrame: 62 duplicate rows removed. New shape: (5000, 7)
Products DataFrame: 0 duplicate rows removed. New shape: (100, 7)
Interactions DataFrame: 1250 duplicate rows removed. New shape: (100000, 8)

In [4]:
print("\n### 2.2 Cleaning users_df ###")

# Convert 'age' to numeric
users_df['age'] = pd.to_numeric(users_df['age'], errors='coerce')

# Convert 'signup_date' to datetime
users_df['signup_date'] = pd.to_datetime(users_df['signup_date'], errors='coerce')

# Standardize 'gender' column
users_df['gender'] = users_df['gender'].str.lower().str.strip()
# Mapping variations if necessary (example, if 'm' and 'male' exist, map to 'male')
# For now, just lowercasing and stripping whitespace as per instruction

# Clean 'email' and 'city' columns by stripping whitespace
users_df['email'] = users_df['email'].str.strip()
users_df['city'] = users_df['city'].str.strip()

print("--- Cleaned Users DataFrame ---")
print("First 5 rows:")
display(users_df.head())
print("Column information:")
users_df.info()

### 2.2 Cleaning users_df ###
--- Cleaned Users DataFrame ---
First 5 rows:

,user_id,name,email,gender,age,city,signup_date
0,U01898,Aaron Green,susannelson@example.net,f,19.0,Donnabury,2025-08-25
1,U00878,Jason Jenkins,gainesanthony@example.com,other,26.0,Port Donaldport,2025-08-07
2,U04504,Jeffery Mejia,pwilliams@example.net,f,61.0,Kingville,2024-08-19
3,U04726,Blake Serrano,patricia70@example.net,f,37.0,Amberfurt,2024-12-31
4,U01596,Matthew Ellis,woodwarderin@example.org,f,24.0,New Debbieville,2025-01-06

Column information:
<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 5061
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      4873 non-null   object
 1   name         4864 non-null   object
 2   email        4878 non-null   object
 3   gender       4877 non-null   object
 4   age          4872 non-null   float64
 5   city         4872 non-null   object
 6   signup_date  4879 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 312.5+ KB

In [5]:
print("\n### 2.3 Cleaning products_df ###")

# Standardize 'category' and 'brand' columns
products_df['category'] = products_df['category'].str.strip().str.title()
products_df['brand'] = products_df['brand'].str.strip().str.title()

print("--- Cleaned Products DataFrame ---")
print("First 5 rows:")
display(products_df.head())
print("Column information:")
products_df.info()

### 2.3 Cleaning products_df ###
--- Cleaned Products DataFrame ---
First 5 rows:

,product_id,product_name,category,brand,price,rating,stock_level
0,P001,Purpose Brother Pro,Electronics,Figueroa And Sons,1114.91,2.0,71
1,P002,Dog Chair Pro,Electronics,"Garcia, Yang And Gardner",889.83,1.1,47
2,P003,Performance Knowledge Max,Fashion,Johnson And Sons,762.98,1.1,101
3,P004,Early Mouth v2,Sports,"Johnson, Gonzalez And Santos",338.46,3.4,414
4,P005,Offer Kind Max,Electronics,Cole Llc,1050.23,2.4,79

Column information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    100 non-null    object
 1   product_name  100 non-null    object
 2   category      100 non-null    object
 3   brand         100 non-null    object
 4   price         100 non-null    float64
 5   rating        100 non-null    float64
 6   stock_level   100 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB

In [6]:
print("\n### 2.3 Cleaning interactions_df ###")

# Convert 'timestamp' to datetime
interactions_df['timestamp'] = pd.to_datetime(interactions_df['timestamp'], errors='coerce')

# Convert 'session_duration_sec' to numeric
interactions_df['session_duration_sec'] = pd.to_numeric(interactions_df['session_duration_sec'], errors='coerce')

# Standardize 'action' and 'device' columns
interactions_df['action'] = interactions_df['action'].str.strip().str.lower()
interactions_df['device'] = interactions_df['device'].str.strip().str.lower()

print("--- Cleaned Interactions DataFrame ---")
print("First 5 rows:")
display(interactions_df.head())
print("Column information:")
interactions_df.info()

### 2.3 Cleaning interactions_df ###
--- Cleaned Interactions DataFrame ---
First 5 rows:

,interaction_id,user_id,product_id,action,rating,timestamp,device,session_duration_sec
0,INT00016884,U00787,P089,add_to_cart,NaN,2025-10-28 01:21:14.342041,desktop,873.0
1,INT00069689,U01492,P068,add_to_cart,NaN,2025-12-14 16:16:21.342041,desktop,835.0
2,INT00054155,U00530,P026,view,3.5,NaT,desktop,942.0
3,INT00031470,U01242,P083,view,1.9,2025-11-10 06:03:21.342041,desktop,572.0
4,INT00048782,U02998,P097,click,NaN,2025-11-25 18:20:58.342041,tablet,953.0

Column information:
<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 101249
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   interaction_id        97496 non-null  object
 1   user_id               97540 non-null  object
 2   product_id            97525 non-null  object
 3   action                97516 non-null  object
 4   rating                10069 non-null  object
 5   timestamp             97305 non-null  datetime64[ns]
 6   device                97531 non-null  object
 7   session_duration_sec  97302 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 6.9+ MB

# 3.   Handle Missing Data


*   Address missing values in all datasets.
*   Handle missing user-item interactions in the 'interactions' dataset.
*   Apply appropriate imputation or removal strategies for other missing values in 'users' and 'products' datasets.

In [7]:
print("### Handling Missing Values ###")

# 1. For interactions_df
print("\n--- Interactions DataFrame: Missing values before cleaning ---")
print(interactions_df.isnull().sum())

# Drop rows where any critical interaction column has missing values
initial_interactions_rows = interactions_df.shape[0]
critical_interaction_cols = ['interaction_id', 'user_id', 'product_id', 'action', 'timestamp', 'device', 'session_duration_sec']
interactions_df.dropna(subset=critical_interaction_cols, inplace=True)
print(f"Dropped {initial_interactions_rows - interactions_df.shape[0]} rows with missing critical interaction data from interactions_df.")

print("\n--- Interactions DataFrame: Missing values after cleaning ---")
print(interactions_df.isnull().sum())

# 2. For users_df
print("\n--- Users DataFrame: Missing values before cleaning ---")
print(users_df.isnull().sum())

# Drop rows where user_id is missing
initial_users_rows = users_df.shape[0]
users_df.dropna(subset=['user_id'], inplace=True)
print(f"Dropped {initial_users_rows - users_df.shape[0]} rows with missing user_id from users_df.")

# Impute missing gender with mode
users_df['gender'] = users_df['gender'].fillna(users_df['gender'].mode()[0])

# Impute missing age with median
users_df['age'] = users_df['age'].fillna(users_df['age'].median())

# Impute missing city with mode
users_df['city'] = users_df['city'].fillna(users_df['city'].mode()[0])

# Impute missing name and email with 'unknown'
users_df['name'] = users_df['name'].fillna('unknown')
users_df['email'] = users_df['email'].fillna('unknown')

# Impute missing signup_date with mode
users_df['signup_date'] = users_df['signup_date'].fillna(users_df['signup_date'].mode()[0])

print("\n--- Users DataFrame: Missing values after cleaning ---")
print(users_df.isnull().sum())

# 3. For products_df
print("\n--- Products DataFrame: Missing values before cleaning ---")
print(products_df.isnull().sum())

# Drop rows where product_id is missing
initial_products_rows = products_df.shape[0]
products_df.dropna(subset=['product_id'], inplace=True)
print(f"Dropped {initial_products_rows - products_df.shape[0]} rows with missing product_id from products_df.")

# Impute missing category and brand with mode
products_df['category'] = products_df['category'].fillna(products_df['category'].mode()[0])
products_df['brand'] = products_df['brand'].fillna(products_df['brand'].mode()[0])

# Impute missing price, rating, stock_level with median
products_df['price'] = products_df['price'].fillna(products_df['price'].median())
products_df['rating'] = products_df['rating'].fillna(products_df['rating'].median())
products_df['stock_level'] = products_df['stock_level'].fillna(products_df['stock_level'].median())

print("\n--- Products DataFrame: Missing values after cleaning ---")
print(products_df.isnull().sum())

### Handling Missing Values ###

--- Interactions DataFrame: Missing values before cleaning ---
interaction_id           2504
user_id                  2460
product_id               2475
action                   2484
rating                  89931
timestamp                2695
device                   2469
session_duration_sec     2698
dtype: int64
Dropped 16520 rows with missing critical interaction data from interactions_df.

--- Interactions DataFrame: Missing values after cleaning ---
interaction_id              0
user_id                     0
product_id                  0
action                      0
rating                  75093
timestamp                   0
device                      0
session_duration_sec        0
dtype: int64

--- Users DataFrame: Missing values before cleaning ---
user_id        127
name           136
email          122
gender         123
age            128
city           128
signup_date    121
dtype: int64
Dropped 127 rows with missing user_id from users_df.

--- Users DataFrame: Missing values after cleaning ---
user_id        0
name           0
email          0
gender         0
age            0
city           0
signup_date    0
dtype: int64

--- Products DataFrame: Missing values before cleaning ---
product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
stock_level     0
dtype: int64
Dropped 0 rows with missing product_id from products_df.

--- Products DataFrame: Missing values after cleaning ---
product_id      0
product_name    0
category        0
brand           0
price           0
rating          0
stock_level     0
dtype: int64

# 4.   Encode Categorical Attributes


*   Apply suitable encoding techniques
*   Apply One-Hot Encoding and Label Encoding techniques
*   To categorical columns such as 'gender', 'city', 'category', 'brand', and 'action'.

In [8]:
print("\n### Encoding Categorical Attributes ###")

# 1. Encode users_df
print("\n--- Encoding users_df ---")
# categorical_cols_users = ['gender', 'city']
categorical_cols_users = ['gender']
cols_to_encode_users = [col for col in categorical_cols_users if col in users_df.columns]

if cols_to_encode_users:
    users_df = pd.get_dummies(users_df, columns=cols_to_encode_users, drop_first=True)
else:
    print(f"Columns {categorical_cols_users} not found in users_df, skipping encoding for these columns.")

print("First 5 rows of users_df after encoding:")
display(users_df.head())
print("Column information of users_df after encoding:")
users_df.info()

# 2. Encode products_df
print("\n--- Encoding products_df ---")
#categorical_cols_products = ['category', 'brand']
categorical_cols_products = ['category']
cols_to_encode_products = [col for col in categorical_cols_products if col in products_df.columns]

if cols_to_encode_products:
    products_df = pd.get_dummies(products_df, columns=cols_to_encode_products, drop_first=True)
else:
    print(f"Columns {categorical_cols_products} not found in products_df, skipping encoding for these columns.")

print("First 5 rows of products_df after encoding:")
display(products_df.head())
print("Column information of products_df after encoding:")
products_df.info()

# 3. Encode interactions_df
print("\n--- Encoding interactions_df ---")
categorical_cols_interactions = ['action', 'device']
cols_to_encode_interactions = [col for col in categorical_cols_interactions if col in interactions_df.columns]

if cols_to_encode_interactions:
    interactions_df = pd.get_dummies(interactions_df, columns=cols_to_encode_interactions, drop_first=True)
else:
    print(f"Columns {categorical_cols_interactions} not found in interactions_df, skipping encoding for these columns.")

print("First 5 rows of interactions_df after encoding:")
display(interactions_df.head())
print("Column information of interactions_df after encoding:")
interactions_df.info()

### Encoding Categorical Attributes ###

--- Encoding users_df ---
First 5 rows of users_df after encoding:

,user_id,name,email,age,city,signup_date,gender_invalid_data,gender_m,gender_other
0,U01898,Aaron Green,susannelson@example.net,19.0,Donnabury,2025-08-25,False,False,False
1,U00878,Jason Jenkins,gainesanthony@example.com,26.0,Port Donaldport,2025-08-07,False,False,True
2,U04504,Jeffery Mejia,pwilliams@example.net,61.0,Kingville,2024-08-19,False,False,False
3,U04726,Blake Serrano,patricia70@example.net,37.0,Amberfurt,2024-12-31,False,False,False
4,U01596,Matthew Ellis,woodwarderin@example.org,24.0,New Debbieville,2025-01-06,False,False,False

Column information of users_df after encoding:
<class 'pandas.core.frame.DataFrame'>
Index: 4873 entries, 0 to 5061
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              4873 non-null   object
 1   name                 4873 non-null   object
 2   email                4873 non-null   object
 3   age                  4873 non-null   float64
 4   city                 4873 non-null   object
 5   signup_date          4873 non-null   datetime64[ns]
 6   gender_invalid_data  4873 non-null   bool
 7   gender_m             4873 non-null   bool
 8   gender_other         4873 non-null   bool
dtypes: bool(3), datetime64[ns](1), float64(1), object(4)
memory usage: 280.8+ KB

--- Encoding products_df ---
First 5 rows of products_df after encoding:

,product_id,product_name,brand,price,rating,stock_level,category_Electronics,category_Fashion,category_Home,category_Sports
0,P001,Purpose Brother Pro,Figueroa And Sons,1114.91,2.0,71,True,False,False,False
1,P002,Dog Chair Pro,"Garcia, Yang And Gardner",889.83,1.1,47,True,False,False,False
2,P003,Performance Knowledge Max,Johnson And Sons,762.98,1.1,101,False,True,False,False
3,P004,Early Mouth v2,"Johnson, Gonzalez And Santos",338.46,3.4,414,False,False,False,True
4,P005,Offer Kind Max,Cole Llc,1050.23,2.4,79,True,False,False,False

Column information of products_df after encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            100 non-null    object
 1   product_name          100 non-null    object
 2   brand                 100 non-null    object
 3   price                 100 non-null    float64
 4   rating                100 non-null    float64
 5   stock_level           100 non-null    int64
 6   category_Electronics  100 non-null    bool
 7   category_Fashion      100 non-null    bool
 8   category_Home         100 non-null    bool
 9   category_Sports       100 non-null    bool
dtypes: bool(4), float64(2), int64(1), object(3)
memory usage: 5.2+ KB

--- Encoding interactions_df ---
First 5 rows of interactions_df after encoding:

,interaction_id,user_id,product_id,rating,timestamp,session_duration_sec,action_click,action_invalid_data,action_purchase,action_view,device_invalid_data,device_mobile,device_tablet
0,INT00016884,U00787,P089,NaN,2025-10-28 01:21:14.342041,873.0,False,False,False,False,False,False,False
1,INT00069689,U01492,P068,NaN,2025-12-14 16:16:21.342041,835.0,False,False,False,False,False,False,False
3,INT00031470,U01242,P083,1.9,2025-11-10 06:03:21.342041,572.0,False,False,False,True,False,False,False
4,INT00048782,U02998,P097,NaN,2025-11-25 18:20:58.342041,953.0,True,False,False,False,False,False,True
5,INT00050861,U01481,P097,NaN,2025-11-27 15:24:40.342041,896.0,True,False,False,False,False,False,True

Column information of interactions_df after encoding:
<class 'pandas.core.frame.DataFrame'>
Index: 83480 entries, 0 to 101249
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   interaction_id        83480 non-null  object
 1   user_id               83480 non-null  object
 2   product_id            83480 non-null  object
 3   rating                8387 non-null   object
 4   timestamp             83480 non-null  datetime64[ns]
 5   session_duration_sec  83480 non-null  float64
 6   action_click          83480 non-null  bool
 7   action_invalid_data   83480 non-null  bool
 8   action_purchase       83480 non-null  bool
 9   action_view           83480 non-null  bool
 10  device_invalid_data   83480 non-null  bool
 11  device_mobile         83480 non-null  bool
 12  device_tablet         83480 non-null  bool
dtypes: bool(7), datetime64[ns](1), float64(1), object(4)
memory usage: 5.0+ MB

# 5.   Normalize Numerical Variables


*   Normalize numerical features like 'age', 'price', 'rating', 'stock_level', 'timestamp', and 'session_duration_sec' to a common scale
*   Prepare them for analysis

In [9]:
print("\n### Normalizing Numerical Variables ###")

# 1. Convert 'signup_date' and 'timestamp' to numerical Unix timestamps
# For users_df
users_df['signup_date_unix'] = users_df['signup_date'].astype('int64') // 10**9

# For interactions_df
interactions_df['timestamp_unix'] = interactions_df['timestamp'].astype('int64') // 10**9

# Initialize MinMaxScaler
scaler = MinMaxScaler()

# 2. Normalize users_df
print("\n--- Normalizing users_df ---")
users_df[['age', 'signup_date_unix']] = scaler.fit_transform(users_df[['age', 'signup_date_unix']])
print("First 5 rows of users_df after normalization:")
display(users_df.head())
print("Column information of users_df after normalization:")
users_df.info()

# 3. Normalize products_df
print("\n--- Normalizing products_df ---")
products_df[['price', 'rating', 'stock_level']] = scaler.fit_transform(products_df[['price', 'rating', 'stock_level']])
print("First 5 rows of products_df after normalization:")
display(products_df.head())
print("Column information of products_df after normalization:")
products_df.info()

# 4. Normalize interactions_df
print("\n--- Normalizing interactions_df ---")
interactions_df[['session_duration_sec', 'timestamp_unix']] = scaler.fit_transform(interactions_df[['session_duration_sec', 'timestamp_unix']])

# 5. Rename timestamp columns in interactions_df
print("\n### Renaming columns in interactions_df ###")
interactions_df.rename(columns={'timestamp': 'event_timestamp', 'timestamp_unix': 'event_timestamp_unix'}, inplace=True)
print("Columns renamed successfully. Displaying first 5 rows and info:")
display(interactions_df.head())
interactions_df.info()

print("\nFirst 5 rows of interactions_df after normalization:")
display(interactions_df.head())
print("Column information of interactions_df after normalization:")
interactions_df.info()

### Normalizing Numerical Variables ###

--- Normalizing users_df ---
First 5 rows of users_df after normalization:

,user_id,name,email,age,city,signup_date,gender_invalid_data,gender_m,gender_other,signup_date_unix
0,U01898,Aaron Green,susannelson@example.net,0.019231,Donnabury,2025-08-25,False,False,False,0.812329
1,U00878,Jason Jenkins,gainesanthony@example.com,0.153846,Port Donaldport,2025-08-07,False,False,True,0.787671
2,U04504,Jeffery Mejia,pwilliams@example.net,0.826923,Kingville,2024-08-19,False,False,False,0.304110
3,U04726,Blake Serrano,patricia70@example.net,0.365385,Amberfurt,2024-12-31,False,False,False,0.487671
4,U01596,Matthew Ellis,woodwarderin@example.org,0.115385,New Debbieville,2025-01-06,False,False,False,0.495890

Column information of users_df after normalization:
<class 'pandas.core.frame.DataFrame'>
Index: 4873 entries, 0 to 5061
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   user_id              4873 non-null   object
 1   name                 4873 non-null   object
 2   email                4873 non-null   object
 3   age                  4873 non-null   float64
 4   city                 4873 non-null   object
 5   signup_date          4873 non-null   datetime64[ns]
 6   gender_invalid_data  4873 non-null   bool
 7   gender_m             4873 non-null   bool
 8   gender_other         4873 non-null   bool
 9   signup_date_unix     4873 non-null   float64
dtypes: bool(3), datetime64[ns](1), float64(2), object(4)
memory usage: 318.8+ KB

--- Normalizing products_df ---
First 5 rows of products_df after normalization:

,product_id,product_name,brand,price,rating,stock_level,category_Electronics,category_Fashion,category_Home,category_Sports
0,P001,Purpose Brother Pro,Figueroa And Sons,0.748972,0.250,0.133333,True,False,False,False
1,P002,Dog Chair Pro,"Garcia, Yang And Gardner",0.596051,0.025,0.084848,True,False,False,False
2,P003,Performance Knowledge Max,Johnson And Sons,0.509868,0.025,0.193939,False,True,False,False
3,P004,Early Mouth v2,"Johnson, Gonzalez And Santos",0.221446,0.600,0.826263,False,False,False,True
4,P005,Offer Kind Max,Cole Llc,0.705028,0.350,0.149495,True,False,False,False

Column information of products_df after normalization:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_id            100 non-null    object
 1   product_name          100 non-null    object
 2   brand                 100 non-null    object
 3   price                 100 non-null    float64
 4   rating                100 non-null    float64
 5   stock_level           100 non-null    float64
 6   category_Electronics  100 non-null    bool
 7   category_Fashion      100 non-null    bool
 8   category_Home         100 non-null    bool
 9   category_Sports       100 non-null    bool
dtypes: bool(4), float64(3), object(3)
memory usage: 5.2+ KB

--- Normalizing interactions_df ---

### Renaming columns in interactions_df ###
Columns renamed successfully. Displaying first 5 rows and info:

,interaction_id,user_id,product_id,rating,event_timestamp,session_duration_sec,action_click,action_invalid_data,action_purchase,action_view,device_invalid_data,device_mobile,device_tablet,event_timestamp_unix
0,INT00016884,U00787,P089,NaN,2025-10-28 01:21:14.342041,0.483565,False,False,False,False,False,False,False,0.168544
1,INT00069689,U01492,P068,NaN,2025-12-14 16:16:21.342041,0.462396,False,False,False,False,False,False,False,0.697686
3,INT00031470,U01242,P083,1.9,2025-11-10 06:03:21.342041,0.315877,False,False,False,True,False,False,False,0.315169
4,INT00048782,U02998,P097,NaN,2025-11-25 18:20:58.342041,0.528134,True,False,False,False,False,False,True,0.487531
5,INT00050861,U01481,P097,NaN,2025-11-27 15:24:40.342041,0.496379,True,False,False,False,False,False,True,0.508394

<class 'pandas.core.frame.DataFrame'>
Index: 83480 entries, 0 to 101249
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   interaction_id        83480 non-null  object
 1   user_id               83480 non-null  object
 2   product_id            83480 non-null  object
 3   rating                8387 non-null   object
 4   event_timestamp       83480 non-null  datetime64[ns]
 5   session_duration_sec  83480 non-null  float64
 6   action_click          83480 non-null  bool
 7   action_invalid_data   83480 non-null  bool
 8   action_purchase       83480 non-null  bool
 9   action_view           83480 non-null  bool
 10  device_invalid_data   83480 non-null  bool
 11  device_mobile         83480 non-null  bool
 12  device_tablet         83480 non-null  bool
 13  event_timestamp_unix  83480 non-null  float64
dtypes: bool(7), datetime64[ns](1), float64(2), object(4)
memory usage: 5.7+ MB

First 5 rows of interactions_df after normalization:

,interaction_id,user_id,product_id,rating,event_timestamp,session_duration_sec,action_click,action_invalid_data,action_purchase,action_view,device_invalid_data,device_mobile,device_tablet,event_timestamp_unix
0,INT00016884,U00787,P089,NaN,2025-10-28 01:21:14.342041,0.483565,False,False,False,False,False,False,False,0.168544
1,INT00069689,U01492,P068,NaN,2025-12-14 16:16:21.342041,0.462396,False,False,False,False,False,False,False,0.697686
3,INT00031470,U01242,P083,1.9,2025-11-10 06:03:21.342041,0.315877,False,False,False,True,False,False,False,0.315169
4,INT00048782,U02998,P097,NaN,2025-11-25 18:20:58.342041,0.528134,True,False,False,False,False,False,True,0.487531
5,INT00050861,U01481,P097,NaN,2025-11-27 15:24:40.342041,0.496379,True,False,False,False,False,False,True,0.508394

Column information of interactions_df after normalization:
<class 'pandas.core.frame.DataFrame'>
Index: 83480 entries, 0 to 101249
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   interaction_id        83480 non-null  object
 1   user_id               83480 non-null  object
 2   product_id            83480 non-null  object
 3   rating                8387 non-null   object
 4   event_timestamp       83480 non-null  datetime64[ns]
 5   session_duration_sec  83480 non-null  float64
 6   action_click          83480 non-null  bool
 7   action_invalid_data   83480 non-null  bool
 8   action_purchase       83480 non-null  bool
 9   action_view           83480 non-null  bool
 10  device_invalid_data   83480 non-null  bool
 11  device_mobile         83480 non-null  bool
 12  device_tablet         83480 non-null  bool
 13  event_timestamp_unix  83480 non-null  float64
dtypes: bool(7), datetime64[ns](1), float64(2), object(4)
memory usage: 5.7+ MB

# 6.   EDA (Exploratory Data Analysis) and Visualization


*   Conduct exploratory data analysis to:
*   Understand interaction distributions (e.g., by action, device, session duration),
*   Identify item popularity,
*   Analyze sparsity patterns in user-item interactions.
*   Generate summary plots such as **histograms** for **numerical distributions**, **bar charts** for **categorical distributions**, and potentially **heatmaps** for **correlations**

In [ ]:
print("### Exploratory Data Analysis and Visualization ###")

# Set plot style for better aesthetics
sns.set_style("whitegrid")

# 1. For interactions_df
print("\n--- Analyzing Interactions Data ---")

# a. Distribution of interaction action types
action_cols = [col for col in interactions_df.columns if col.startswith('action_')]
action_counts = interactions_df[action_cols].sum()
action_labels = [col.replace('action_', '').replace('_', ' ').title() for col in action_cols]

plt.figure(figsize=(10, 6))
sns.barplot(x=action_labels, y=action_counts.values, hue=action_labels, palette='viridis', legend=False)
plt.title('Distribution of Interaction Action Types')
plt.xlabel('Action Type')
plt.ylabel('Number of Interactions')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()
plt.close()

# b. Distribution of interaction device types
device_cols = [col for col in interactions_df.columns if col.startswith('device_')]
device_counts = interactions_df[device_cols].sum()
device_labels = [col.replace('device_', '').replace('_', ' ').title() for col in device_cols]

plt.figure(figsize=(10, 6))
sns.barplot(x=device_labels, y=device_counts.values, hue=device_labels, palette='viridis', legend=False)
plt.title('Distribution of Interaction Device Types')
plt.xlabel('Device Type')
plt.ylabel('Number of Interactions')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()
plt.close()

# c. Histogram for session_duration_sec
plt.figure(figsize=(10, 6))
sns.histplot(interactions_df['session_duration_sec'], bins=50, kde=True, color='skyblue')
plt.title('Distribution of Session Duration (seconds)')
plt.xlabel('Session Duration (normalized seconds)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
plt.close()

# d. Top 10 most interacted product_ids
top_products = interactions_df['product_id'].value_counts().head(10)

plt.figure(figsize=(12, 7))
sns.barplot(x=top_products.index, y=top_products.values, hue=top_products.index, palette='magma', legend=False)
plt.title('Top 10 Most Interacted Products')
plt.xlabel('Product ID')
plt.ylabel('Number of Interactions')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()
plt.close()

# 2. For users_df
print("\n--- Analyzing Users Data ---")

# a. Histogram for age distribution
plt.figure(figsize=(10, 6))
sns.histplot(users_df['age'], bins=30, kde=True, color='lightcoral')
plt.title('Distribution of User Age')
plt.xlabel('Age (normalized)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
plt.close()

# 3. For products_df
print("\n--- Analyzing Products Data ---")

# a. Histogram for price distribution
plt.figure(figsize=(10, 6))
sns.histplot(products_df['price'], bins=30, kde=True, color='lightgreen')
plt.title('Distribution of Product Prices')
plt.xlabel('Price (normalized)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
plt.close()

# b. Correlation heatmap for numerical columns
correlation_matrix = products_df[['price', 'rating', 'stock_level']].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Correlation Heatmap of Product Numerical Attributes')
plt.tight_layout()
plt.show()
plt.close()

print("\n✅ All visualizations completed successfully!")

### Exploratory Data Analysis and Visualization ###

--- Analyzing Interactions Data ---

ModuleNotFoundError: No module named 'matplotlib_inline'

# 7.   Save Cleaned Datasets


*   Save the cleaned and preprocessed 'users', 'products', and 'interactions' DataFrames into new CSV files
*   Data is now ready for further transformation or model building.

In [ ]:
import os

# 1. Define the directory path
# output_dir = '/content/drive/MyDrive/Sem-2/DMML/DMML-Group-4/data/cleaned/'
# os.makedirs(output_dir, exist_ok=True)

# 2. Save users_df
users_output_path = os.path.join(PROCESSED_USERS_DIR, 'users_cleaned.csv')
users_df.to_csv(users_output_path, index=False)
print(f"Cleaned users_df saved to: {users_output_path}")

# 3. Save products_df
products_output_path = os.path.join(PROCESSED_PRODUCT_DIR, 'products_cleaned.csv')
products_df.to_csv(products_output_path, index=False)
print(f"Cleaned products_df saved to: {products_output_path}")

# 4. Save interactions_df
interactions_output_path = os.path.join(PROCESSED_INTERACTION_DIR, 'interactions_cleaned.csv')
interactions_df.to_csv(interactions_output_path, index=False)
print(f"Cleaned interactions_df saved to: {interactions_output_path}")